# -*- coding: utf-8 -*-
"""Data Analysis on CSV Files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G436kdcEMG2T-b9FUyGdRjONKmSP-Dfl
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('pizza_sales.csv')

df.head()

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, errors='coerce')

df['month'] = df['order_date'].dt.to_period('M')

sales_by_category = df.groupby('pizza_category')['total_price'].sum().reset_index()

print(sales_by_category)

monthly_sales = df.groupby('month')['total_price'].sum().reset_index()
print(monthly_sales)

most_sold_pizzas = df.groupby('pizza_name')['quantity'].sum().reset_index().sort_values(by='quantity',ascending=False)
print(most_sold_pizzas.head(10))

sns.set(style="whitegrid")

plt.figure(figsize=(8,5))
sns.barplot(data=sales_by_category, x='pizza_category', y='total_price', palette='viridis')
plt.title('Total Sales by Pizza Category')
plt.xlabel('Category')
plt.ylabel('Sales')
plt.tight_layout()
plt.show()

top10 = most_sold_pizzas.head(10)

plt.figure(figsize=(12,6))
sns.barplot(data=top10, x='quantity', y='pizza_name', palette='magma')
plt.title('Top 10 Most Sold Pizzas')
plt.xlabel('Quantity Sold')
plt.ylabel('Pizza')
plt.tight_layout()
plt.show()